"use client"

import { useState } from "react"
import { Brain, Github, ExternalLink, AlertCircle, CheckCircle2 } from "lucide-react"
import { Button } from "./components/ui/button"
import { Textarea } from "./components/ui/textarea"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./components/ui/card"
import { Badge } from "./components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs"
import { Slider } from "./components/ui/slider"
import "./App.css"

function App() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b">
        <div className="container mx-auto py-4 px-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Brain className="h-6 w-6 text-purple-600" />
            <span className="font-bold text-xl">AI Detector</span>
          </div>
          <div className="flex items-center gap-4">
            <a href="#about" className="text-sm font-medium hover:text-purple-600 transition-colors">
              About
            </a>
            <a href="#team" className="text-sm font-medium hover:text-purple-600 transition-colors">
              Team
            </a>
            <Button size="sm" variant="outline" className="gap-2">
              <Github className="h-4 w-4" />
              <span className="hidden sm:inline">GitHub</span>
            </Button>
          </div>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero Section */}
        <section className="bg-gradient-to-b from-purple-50 to-white py-16 md:py-24">
          <div className="container mx-auto px-4 text-center">
            <Badge variant="outline" className="mb-4 px-3 py-1 text-purple-600 border-purple-200 bg-purple-50">
              JustWork Hackathon Entry
            </Badge>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-purple-600 to-indigo-600">
              AI Text Detector
            </h1>
            <p className="text-lg md:text-xl text-gray-600 max-w-3xl mx-auto mb-8">
              Instantly analyze text to determine if it was written by a human or generated by AI. Our advanced
              algorithm helps identify AI-generated content with high accuracy.
            </p>
            <Button className="bg-purple-600 hover:bg-purple-700 text-white px-6 py-6 rounded-lg text-lg">
              Try It Now
            </Button>
          </div>
        </section>

        {/* Text Analysis Section */}
        <section className="py-16" id="detector">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <TextAnalyzer />
            </div>
          </div>
        </section>

        {/* About Section */}
        <section className="py-16 bg-gray-50" id="about">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">About This Project</h2>
              <p className="text-gray-600">
                This AI text detector was created for the Traderly hackathon challenge. Our tool uses advanced machine
                learning algorithms to analyze text patterns, vocabulary usage, and structural elements to determine
                whether content was written by a human or generated by AI.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              <Card>
                <CardHeader>
                  <CardTitle>Accurate Detection</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600">
                    Our model has been trained on thousands of samples to accurately distinguish between human and
                    AI-written text.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Fast Analysis</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600">
                    Get results in seconds, no matter how long the text. Our algorithm is optimized for speed and
                    efficiency.
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Privacy First</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600">
                    We don't store your text. All analysis happens in your browser, ensuring your content remains
                    private.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>

        {/* Team Section */}
        <section className="py-16" id="team">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl mx-auto text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Team JustWork</h2>
              <p className="text-gray-600">
                We're a passionate team of developers participating in the Traderly hackathon challenge.
              </p>
            </div>

            <div className="max-w-4xl mx-auto">
              <Card>
                <CardHeader>
                  <CardTitle>About the Challenge</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 mb-4">
                    The Traderly hackathon challenged teams to create innovative tools that address the growing presence
                    of AI in our digital landscape. Our team, JustWork, decided to tackle the problem of distinguishing
                    between human and AI-generated content.
                  </p>
                  <p className="text-gray-600">
                    As AI text generators become more sophisticated, the ability to identify AI-written content becomes
                    increasingly important for maintaining authenticity and trust online.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button variant="outline" className="gap-2">
                    <ExternalLink className="h-4 w-4" />
                    Learn more about Traderly
                  </Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
      </main>

      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <Brain className="h-6 w-6 text-purple-400" />
              <span className="font-bold text-xl">AI Detector</span>
            </div>
            <div className="text-gray-400 text-sm">
              Created by Team JustWork for the Traderly Hackathon &copy; {new Date().getFullYear()}
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function TextAnalyzer() {
  const [text, setText] = useState("")
  const [result, setResult] = useState(null)
  const [isAnalyzing, setIsAnalyzing] = useState(false)

  const analyzeText = () => {
    if (!text.trim()) return

    setIsAnalyzing(true)

    // Simulate analysis with a timeout
    setTimeout(() => {
      // This is a mock result - in a real app, you'd call an API or use a model
      const aiProbability = Math.random() * 100
      setResult({
        aiProbability,
        isAI: aiProbability > 65,
        confidence: aiProbability > 85 || aiProbability < 15 ? "high" : "medium",
        textLength: text.length,
        wordCount: text.trim().split(/\s+/).length,
      })
      setIsAnalyzing(false)
    }, 1500)
  }

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle>AI Text Detector</CardTitle>
        <CardDescription>
          Paste any text below to analyze whether it was written by a human or generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Textarea
          placeholder="Paste text here to analyze (minimum 100 characters for accurate results)..."
          className="min-h-[200px] mb-4"
          value={text}
          onChange={(e) => setText(e.target.value)}
        />

        <Button
          onClick={analyzeText}
          className="w-full bg-purple-600 hover:bg-purple-700"
          disabled={isAnalyzing || text.length < 50}
        >
          {isAnalyzing ? "Analyzing..." : "Analyze Text"}
        </Button>

        {result && (
          <div className="mt-8">
            <Tabs defaultValue="result">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="result">Result</TabsTrigger>
                <TabsTrigger value="details">Analysis Details</TabsTrigger>
              </TabsList>
              <TabsContent value="result" className="pt-6">
                <div className="flex flex-col items-center text-center">
                  {result.isAI ? (
                    <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-full">
                      <AlertCircle className="h-12 w-12" />
                    </div>
                  ) : (
                    <div className="mb-4 p-3 bg-green-50 text-green-700 rounded-full">
                      <CheckCircle2 className="h-12 w-12" />
                    </div>
                  )}

                  <h3 className="text-2xl font-bold mb-2">
                    {result.isAI ? "AI-Generated Text Detected" : "Human-Written Text Detected"}
                  </h3>

                  <p className="text-gray-600 mb-6">
                    {result.isAI
                      ? "This text was likely generated by an AI tool like ChatGPT, Claude, or similar."
                      : "This text was likely written by a human author."}
                  </p>

                  <div className="w-full max-w-md">
                    <div className="flex justify-between mb-2">
                      <span className="text-sm font-medium">Human</span>
                      <span className="text-sm font-medium">AI</span>
                    </div>
                    <div className="relative pt-1 mb-6">
                      <Slider defaultValue={[result.aiProbability]} max={100} step={1} disabled />
                    </div>
                    <div className="text-center">
                      <Badge variant={result.isAI ? "destructive" : "outline"} className="mb-2">
                        {result.confidence.toUpperCase()} CONFIDENCE
                      </Badge>
                      <p className="text-sm text-gray-500">
                        {result.aiProbability.toFixed(1)}% probability of being AI-generated
                      </p>
                    </div>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="details" className="pt-6">
                <div className="space-y-4">
                  <div>
                    <h3 className="font-medium mb-2">Text Statistics</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <div className="text-sm text-gray-500">Characters</div>
                        <div className="text-2xl font-bold">{result.textLength}</div>
                      </div>
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <div className="text-sm text-gray-500">Words</div>
                        <div className="text-2xl font-bold">{result.wordCount}</div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h3 className="font-medium mb-2">Analysis Factors</h3>
                    <ul className="space-y-2 text-sm text-gray-600">
                      <li className="flex items-start gap-2">
                        <div className="mt-0.5 h-4 w-4 rounded-full bg-purple-100 flex items-center justify-center">
                          <div className="h-2 w-2 rounded-full bg-purple-600"></div>
                        </div>
                        <span>Pattern recognition of common AI writing structures</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <div className="mt-0.5 h-4 w-4 rounded-full bg-purple-100 flex items-center justify-center">
                          <div className="h-2 w-2 rounded-full bg-purple-600"></div>
                        </div>
                        <span>Vocabulary diversity and usage patterns</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <div className="mt-0.5 h-4 w-4 rounded-full bg-purple-100 flex items-center justify-center">
                          <div className="h-2 w-2 rounded-full bg-purple-600"></div>
                        </div>
                        <span>Sentence structure and complexity analysis</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <div className="mt-0.5 h-4 w-4 rounded-full bg-purple-100 flex items-center justify-center">
                          <div className="h-2 w-2 rounded-full bg-purple-600"></div>
                        </div>
                        <span>Contextual coherence evaluation</span>
                      </li>
                    </ul>
                  </div>

                  <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-amber-800 text-sm">
                    <p className="font-medium mb-1">Disclaimer</p>
                    <p>
                      This is a demonstration tool and may not be 100% accurate. AI detection technology is constantly
                      evolving as AI text generators improve. For critical applications, consider using multiple
                      detection methods.
                    </p>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

export default App
